### ISSUE TITLE
[Issue]: Bin Duplicator only randomize the first

### ISSUE THREAD

**Issue by Darkshadow3582** [HiddenRamblings/TagMo#687] opened 2023-05-20 21:32 UTC
### Issue Description

When the Bin duplicator is executed and duplicate 3, only one of them is randomized

example
original - Serial xxxx809
1 duplicate - Serial xxxx770
2 duplicate - Serial xxxx770
3 duplicate - Serial xxxx770

**Comment by AbandonedCart** [comment] 2023-05-20 21:34
duplicate of https://github.com/HiddenRamblings/TagMo/issues/674

**Closed by AbandonedCart** 2023-05-20 21:34 UTC
Labels: Entomology
