### ISSUE TITLE
[Issue]: Flask response is truncated

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#571] opened 2022-09-21 19:07 UTC
### Issue Description

Change to flask tab, sits saying connecting.

### Logcat Output

```shell
TagMo - #0adbe59
Android TIRAMISU (13)
5.46 GB RAM
Installed by release

--------- beginning of main
09-21 14:05:31.340  6053  6053 E .tagmo.eightbit: Not starting debugger since process cannot load the jdwp agent.
09-21 14:05:31.828  6053  6080 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
09-21 14:05:31.828  6053  6080 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
09-21 14:05:31.989  6053  6053 W View    : requestLayout() improperly called by android.widget.FrameLayout{970421c V.E..V... ......ID 0,0-1080,1918 #2} during layout: running second layout pass
09-21 14:05:31.989  6053  6053 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{698de25 VFED.V... ......ID 0,0-1080,1726 #7f09005f app:id/amiibos_list} during layout: running second layout pass
09-21 14:05:31.989  6053  6053 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{8640bfa VFED.V... ......ID 0,1803-1080,1915 #7f09010f app:id/foomiibo_list} during layout: running second layout pass
09-21 14:05:32.043  6053  6080 W Parcel  : Expecting binder but got null!
09-21 14:05:34.095  6053  6053 W BottomSheetBehavior: Cannot set state: 5
09-21 14:05:34.360  6053  6053 W RecyclerView: No adapter attached; skipping layout
09-21 14:05:42.642  6053  6053 W View    : requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{4708883 V.ED..... ......ID 198,40-329,114} during layout: running second layout pass
09-21 14:05:42.642  6053  6053 W View    : requestLayout() improperly called by androidx.recyclerview.widget.RecyclerView{5d43a00 VFED.V... ......ID 0,231-1080,330 #7f090108 app:id/flask_details} during layout: running second layout pass
09-21 14:05:42.643  6053  6053 W RecyclerView: No adapter attached; skipping layout
09-21 14:05:42.961  6053  6508 W System.err: org.json.JSONException: Unterminated array at character 160 of [ 
  "Inkling Boy \- |nq22q|0", 
  "Inkling Girl \-|nonia|0", 
  "Inkling Squid |nrgn6|0", 
  "Inkling Boy \- |y3p4y|0", 
  "Inkling Girl \-|y2aki|0",  ... 
  "Inkling Boy|2giki|0", 
  "Inkling Girl|2f402|0", 
  "Inkling Squid|2hx4y|0", 
  "Callie|nlude|0", 
  "Marie|nn8xu|0"
 ]
09-21 14:05:42.961  6053  6508 W System.err: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
09-21 14:05:42.961  6053  6508 W System.err: 	at org.json.JSONTokener.readArray(JSONTokener.java:450)
09-21 14:05:42.961  6053  6508 W System.err: 	at org.json.JSONTokener.nextValue(JSONTokener.java:107)
09-21 14:05:42.961  6053  6508 W System.err: 	at org.json.JSONArray.<init>(JSONArray.java:94)
09-21 14:05:42.962  6053  6508 W System.err: 	at org.json.JSONArray.<init>(JSONArray.java:110)
09-21 14:05:42.962  6053  6508 W System.err: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.FlaskGattService.getCharacteristicValue(FlaskGattService.java:202)
09-21 14:05:42.962  6053  6508 W System.err: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.FlaskGattService.-$$Nest$mgetCharacteristicValue(Unknown Source:0)
09-21 14:05:42.962  6053  6508 W System.err: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.FlaskGattService$1.onCharacteristicChanged(FlaskGattService.java:302)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.bluetooth.BluetoothGattCallback.onCharacteristicChanged(BluetoothGattCallback.java:159)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:525)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:864)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt.-$$Nest$mrunOrQueueCallback(Unknown Source:0)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:519)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:246)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.os.Binder.execTransactInternal(Binder.java:1285)
09-21 14:05:42.962  6053  6508 W System.err: 	at android.os.Binder.execTransact(Binder.java:1244)
09-21 14:05:43.288  6053  6508 W System.err: org.json.JSONException: Unterminated array at character 160 of [ 
  "Inkling Boy \- |nq22q|0", 
  "Inkling Girl \-|nonia|0", 
  "Inkling Squid |nrgn6|0", 
  "Inkling Boy \- |y3p4y|0", 
  "Inkling Girl \-|y2aki|0",  ... 
  "Inkling Boy|2giki|0", 
  "Inkling Girl|2f402|0", 
  "Inkling Squid|2hx4y|0", 
  "Callie|nlude|0", 
  "Marie|nn8xu|0"
 ]
09-21 14:05:43.288  6053  6508 W System.err: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
09-21 14:05:43.288  6053  6508 W System.err: 	at org.json.JSONTokener.readArray(JSONTokener.java:450)
09-21 14:05:43.288  6053  6508 W System.err: 	at org.json.JSONTokener.nextValue(JSONTokener.java:107)
09-21 14:05:43.288  6053  6508 W System.err: 	at org.json.JSONArray.<init>(JSONArray.java:94)
09-21 14:05:43.288  6053  6508 W System.err: 	at org.json.JSONArray.<init>(JSONArray.java:110)
09-21 14:05:43.288  6053  6508 W System.err: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.FlaskGattService.getCharacteristicValue(FlaskGattService.java:202)
09-21 14:05:43.288  6053  6508 W System.err: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.FlaskGattService.-$$Nest$mgetCharacteristicValue(Unknown Source:0)
09-21 14:05:43.288  6053  6508 W System.err: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.FlaskGattService$1.onCharacteristicChanged(FlaskGattService.java:302)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.bluetooth.BluetoothGattCallback.onCharacteristicChanged(BluetoothGattCallback.java:159)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:525)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:864)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt.-$$Nest$mrunOrQueueCallback(Unknown Source:0)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:519)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:246)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.os.Binder.execTransactInternal(Binder.java:1285)
09-21 14:05:43.288  6053  6508 W System.err: 	at android.os.Binder.execTransact(Binder.java:1244)
09-21 14:05:51.949  6053  6080 W Parcel  : Expecting binder but got null!
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment] 2022-09-21 19:36
Weird naming conventions seem to be gumming up the read.

**Comment by AbandonedCart** [comment] 2022-09-21 20:10
How are your files named? Is it `Inkling Boy (Neon Green)`, `Inkling Boy: Neon Green`, `Inkling Boy - Neon Green`, something else?

**Comment by AbandonedCart** [comment] 2022-09-21 20:32
Alright, I think I see what is happening. @withgallantry any idea why the JSON truncates at 5 records? It seems to be the same thing that was happening in #501. It's happening in the content returned from the device, because it's visible in the log spam for the cut up chunks.

```
2022-09-21 16:25:49.010 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX tag.getList()
    =[ 
2022-09-21 16:25:49.019 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX   "Shulk|1oef6|0", 
2022-09-21 16:25:49.031 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX 
      "Inkling Boy - |y
2022-09-21 16:25:49.042 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX 3p4y|0", 
      "Callie
2022-09-21 16:25:49.054 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX |nlude|0", 
      "Inkl
2022-09-21 16:25:49.067 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX ing Boy 1|y3p4y|0", 
2022-09-21 16:25:49.076 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX 
      "Inkling Boy - |
2022-09-21 16:25:49.088 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX nq22q|0",  ... 
      "
2022-09-21 16:25:49.098 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX Marina|ylyiq|0", 
     
2022-09-21 16:25:49.114 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX  "Octoling Boy|zjo5e
2022-09-21 16:25:49.121 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX |0", 
      "Octoling G
2022-09-21 16:25:49.137 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX irl|zi9ky|0", 
      "O
2022-09-21 16:25:49.143 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX ctoling Octop|zl2pu|
2022-09-21 16:25:49.155 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX 0", 
      "Pearl|ykjya
2022-09-21 16:25:49.177 7701-7719/com.hiddenramblings.tagmo.eightbit D/FlaskGattService: FlaskRX |0"
     ]
    >
```

**Comment by AbandonedCart** [comment] 2022-09-21 20:36
Yeah, that one was a test because it looked like the escaped characters were causing the issue, but they aren't. Output is getting chopped in half and ellipsized. I think it might be an Android API problem.

**Comment by AbandonedCart** [comment] 2022-09-22 13:46
Still trying to figure out what may be causing this. The information about BLE is a bit fragmented and simplistic. It's more and more common that everyone does everything exactly the same and if it doesn't work, it's assumed impossible. This is ironically also the reason Google is not entirely fond of when I contact them.

**Comment by withgallantry** [comment] 2022-09-22 13:51
This could be an issue on the Flask side. Certain unicode characters truncate the response, like you mentioned above. @sentientmilkshake Does the Flask work on flask.run still? Or does it hang once connected? 
Nothing has changed in terms of how the list is sent. I will investigate with some different tag names, see if I can replicate the issue.

**Comment by withgallantry** [comment] 2022-09-22 14:17
> Everything works as normal. I can still use and edit it from the flask website.

Ok, I'll look into it in the upcoming days.

**Comment by AbandonedCart** [comment] 2022-09-22 14:25
@withgallantry I really don't think it's on your end at all, but just in case you happened to notice something. From what I've seen it may be that using the `WRITE_TYPE_NO_RESPONSE` that got us a response was actually not my best idea because it also limits the character count.

**Comment by AbandonedCart** [comment] 2022-09-29 16:51
That is a side effect of pulling all the changes to retrace the ANR. It'll get fixed once the fragments can be ruled out as the cause.

**Comment by AbandonedCart** [comment] 2022-10-01 00:30
For now, we can assume this is a known issue until a solution is found. It still cuts the middle and the workaround for now is discarding it. Getting a full read is a broken API on Android, so the next best thing will be detecting what was cut and filling it in using one-off calls.

There are two ways and only one may work. I get the API to break the read by offset, which may end up being more mess than it's worth. I get the number of dropped records and retrieve them as single items, which is slower than a bulk read. The question is whether offsets will be any faster or just end up about the same and require more backend.

**Comment by withgallantry** [comment] 2022-10-03 10:58
If there is a solution by adding a new API to the Flask, I'm happy to do that. I don't have much control over the streaming of the data at a low level, I've abstracted it to a high level interface instead. It could be done but would be a lot of work.
Would taking the approach of waiting until a new line character is present to signal the transmission is complete work? I've done that on a system that had a similar issue but I'm not sure if that approach works in Android.

**Comment by AbandonedCart** [comment] 2022-10-03 13:25
It's not that the Flask is doing anything wrong, but that Android is taking the data and summarizing it. I found a low-level version of the API that will retrieve the chunks and build the strings, but it's practically undocumented. It's the method behind the one they crippled.

It's really a perfect example of one of my biggest issues with the Android platform. They forget they are designing an OS and treat it like an app. They wrap the low-level APIs in their convenience methods and then forget that people may actually need all the data they didn't have a use for in their own code. The documentation barely includes any of the real methods, but doesn't do that well at explaining the wrappers, either.

Rather than fix it, they now redirect you to StackOverflow. Most will come across CommonsWare, who can interpret the documentation into code or more readable explanations. At first, he will seem like the resource they were missing, until realizing that he treats the documentation like a holy archive. It can be interpreted, but never contradicted. You should never stray from the documentation or you will suffer dire consequences. It's like Joel Osteen for Android.

This means that anyone looking to do more than exactly what Android proposes inside the neat little box is more or less on their own. Rant aside, it means I need to reinvent the wheel. It will probably end up running faster that way, anyway.

**Comment by AbandonedCart** [comment] 2022-10-14 10:18
I think we have a pretty good grasp on the problem, just not a solution yet. It's always the first and last 5 records, even at varying lengths.

**Comment by AbandonedCart** [comment] 2022-10-14 22:37
@withgallantry Is there an endpoint to get a single item that is not the currently active one? I didn't come across one that I remember, but that would allow filling in the missing records. I'm pretty sure there was one to get the total number of items, unless you are doing that by counting what's returned by getList() but honestly, just iterating until I come to the same hash as the one after the `...` would work without counting (and likely be faster).

**Comment by withgallantry** [comment] 2022-10-18 22:05
Is the truncation predictable? I could introduce a paginated getList that would allow you to get pages of x length tags? If not I can definitely add an API to just get one item.

**Comment by AbandonedCart** [comment] 2022-10-18 23:54
It gives the first 5, the last 5, and ... between. If you delete one, it will add a record to whichever end it came from. If you broke it into 5s, that could work. That's up to you. Thanks.

**Comment by withgallantry** [comment] 2022-10-19 13:39
I've added offset and length to getList, so `tag.getList(0,5);`. Hopefully that will help? If so I'll release the firmware it to beta.flask.run later today.

**Comment by AbandonedCart** [comment] 2022-10-19 13:41
That's perfect. Thanks!

**Comment by AbandonedCart** [comment] 2022-10-19 15:40
Just to make sure, calling `getList` without parameters will still return whatever is there, right? If not, I just need to add an additional call in there, but I think I have things mostly set up to work with the beta firmware and still detect the current one and not freak out.

**Comment by withgallantry** [comment] 2022-10-19 15:45
> Just to make sure, calling `getList` without parameters will still return whatever is there, right? 

Exactly that, calling it with no parameters returns the entire list. I felt it didn't feel like a hack and kept it backwards compatible.

**Comment by AbandonedCart** [comment] 2022-10-19 16:06
Sounds like that should line up. I have to run out in a bit, so I figured I would set up whatever I could to get caught up later. Thanks, again. This should work out pretty well.

**Comment by withgallantry** [comment] 2022-10-20 23:05
That's all live on the main flask.run site now. Connecting will prompt an update.

**Comment by AbandonedCart** [comment] 2022-10-21 00:06
Just did the update. I didn't notice it before, but I like the confetti on the selected slot. That looks great.

**Closed** 2022-10-21 00:28 UTC
Labels: Entomology

**Comment by AbandonedCart** [comment] 2022-10-21 00:58
@withgallantry Once again, you have saved the day. Good work!

**Comment by AbandonedCart** [comment] 2022-10-21 11:30
May be coincidence or bad luck, but it seems I'm stuck on the blank screen. I've tried restoring the firmware a few times, but it hasn't fixed it. Not sure what happened there. The last thing I did was connect to it and view the contents. Changed some code in TagMo, went to connect again, and got an error. Checked the Flask and it was blank.
