### ISSUE TITLE
[Issue]: tried it on a different device, flask still not working

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#632] opened 2022-11-25 03:56 UTC
### Issue Description

Hello. I understood you thought it was my device. so I tried another.it still didn't work. not sure it's the decice. Just trying to help the best I can.

### Logcat Output

```shell
TagMo 3.4.2 (GitHub Release) #8857741
Android Q (10) - 1.77 GB RAM

--------- beginning of main
11-24 21:48:19.240 10406 10406 W main    : type=1400 audit(0.0:165): avc: denied { write } for name="tasks" dev="tmpfs" ino=10885 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=0
11-24 21:48:19.281 10406 10406 E .tagmo.eightbi: Not starting debugger since process cannot load the jdwp agent.
11-24 21:48:21.722 10406 10406 W View    : requestLayout() improperly called by android.widget.FrameLayout{3f1cb96 V.E..V... ......ID 0,0-1080,1605 #2} during layout: running second layout pass
11-24 21:48:21.723 10406 10406 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{4ad0534 VFED.V... ......ID 0,945-1080,1602 #7f090110 app:id/foomiibo_list} during layout: running second layout pass
11-24 21:48:21.723 10406 10406 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{8d24646 VFED.V... ......ID 0,0-1080,945 #7f090082 app:id/browser_content} during layout: running second layout pass
11-24 21:48:21.849 10406 10429 W Gralloc3: mapper 3.x is not supported
11-24 21:48:33.310 10406 10406 W BottomSheetBehavior: Cannot set state: 5
11-24 21:48:33.856 10406 10406 W RecyclerView: No adapter attached; skipping layout
11-24 21:48:34.259 10406 10406 W linker  : Warning: "/data/app/com.google.android.webview-N3xc-o5GRoDyEruoLihxIA==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
11-24 21:48:37.314 10406 10406 W RecyclerView: No adapter attached; skipping layout
11-24 21:48:37.581 10406 10406 W BottomSheetBehavior: Cannot set state: 5
11-24 21:48:37.639 10406 10406 W View    : requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{2ef0c6e V.ED..... ......ID 189,38-316,109} during layout: running second layout pass
11-24 21:48:37.654 10406 10406 W View    : requestLayout() improperly called by androidx.recyclerview.widget.RecyclerView{82d0692 VFED.V... ......ID 0,222-1080,317 #7f090109 app:id/flask_content} during layout: running second layout pass
11-24 21:48:37.661 10406 10406 W RecyclerView: No adapter attached; skipping layout
11-24 21:48:50.396 10406 10406 W RecyclerView: No adapter attached; skipping layout
11-24 21:49:18.321 10406 10547 W System.err: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
11-24 21:49:18.340 10406 10547 W System.err: 	at okhttp3.internal.http2.Http2Stream$FramingSource.checkNotClosed(Http2Stream.java:436)
11-24 21:49:18.341 10406 10547 W System.err: 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:338)
11-24 21:49:18.341 10406 10547 W System.err: 	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
11-24 21:49:18.341 10406 10547 W System.err: 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
11-24 21:49:18.341 10406 10547 W System.err: 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.util.ExceptionPassthroughInputStream.read(ExceptionPassthroughInputStream.java:105)
11-24 21:49:18.341 10406 10547 W System.err: 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:46)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
11-24 21:49:18.341 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
11-24 21:49:18.341 10406 10547 W System.err: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
11-24 21:49:18.341 10406 10547 W System.err: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:790)
11-24 21:49:18.342 10406 10547 W System.err: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:765)
11-24 21:49:18.342 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.ImageReader$InputStreamImageReader.decodeBitmap(ImageReader.java:194)
11-24 21:49:18.342 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:781)
11-24 21:49:18.342 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.getDimensions(Downsampler.java:752)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:317)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:285)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:222)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:539)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:503)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:489)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:434)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:283)
11-24 21:49:18.343 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
11-24 21:49:18.344 10406 10547 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-24 21:49:18.344 10406 10547 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-24 21:49:18.344 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:421)
11-24 21:49:18.344 10406 10547 W System.err: 	at java.lang.Thread.run(Thread.java:919)
11-24 21:49:18.344 10406 10547 W System.err: 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:380)
11-24 21:49:19.615 10406 10406 W BottomSheetBehavior: Cannot set state: 5
11-24 21:49:20.132 10406 10406 W BottomSheetBehavior: Cannot set state: 5
11-24 21:49:20.146 10406 10406 W View    : requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{2ef0c6e V.ED..... ......ID 189,38-316,109} during layout: running second layout pass
11-24 21:49:20.170 10406 10406 W View    : requestLayout() improperly called by androidx.recyclerview.widget.RecyclerView{82d0692 VFED.V... ......ID 0,222-1080,1589 #7f090109 app:id/flask_content} during layout: running second layout pass
11-24 21:49:20.450 10406 10406 W View    : requestLayout() improperly called by android.widget.LinearLayout{32ca6dc V.E..V... ........ 0,0-1048,200} during second layout pass: posting in next frame
11-24 21:49:20.450 10406 10406 W View    : requestLayout() improperly called by android.widget.LinearLayout{2983961 V.E..V... ........ 0,62-827,98 #7f09011d app:id/group1} during second layout pass: posting in next frame
11-24 21:49:20.450 10406 10406 W View    : requestLayout() improperly called by android.widget.LinearLayout{d3e0a9d V.E..V... ........ 0,98-827,134 #7f09011e app:id/group2} during second layout pass: posting in next frame
11-24 21:49:20.450 10406 10406 W View    : requestLayout() improperly called by android.widget.LinearLayout{e726a6a V.E..V... ........ 0,0-1048,200} during second layout pass: posting in next frame
11-24 21:49:20.450 10406 10406 W View    : requestLayout() improperly called by android.widget.LinearLayout{785c237 V.E..V... ........ 0,62-827,98 #7f09011d app:id/group1} during second layout pass: posting in next frame
11-24 21:49:20.450 10406 10406 W View    : requestLayout() improperly called by android.widget.LinearLayout{ea4ad3 V.E..V... ........ 0,98-827,134 #7f09011e app:id/group2} during second layout pass: posting in next frame
11-24 21:49:44.739 10406 10406 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment] 2022-11-25 09:58
The issue, as it has been for nearly a month now, is with Glide. It's an issue with your devices receiving images from the internet, not necessarily one specific device. There is nothing that can be done about it on our end. It's almost impossible to track down the cause because you appear to be the only person across millions experiencing it.

**Comment by AbandonedCart** [comment] 2022-11-25 10:37
Duplicate of -
https://github.com/HiddenRamblings/TagMo/issues/631
https://github.com/HiddenRamblings/TagMo/issues/626
https://github.com/HiddenRamblings/TagMo/issues/607
https://github.com/HiddenRamblings/TagMo/issues/590
https://github.com/HiddenRamblings/TagMo/issues/575
https://github.com/HiddenRamblings/TagMo/issues/573
https://github.com/HiddenRamblings/TagMo/issues/572

**Closed as completed** 2022-12-09 02:28 UTC
Labels: Entomology
