### ISSUE TITLE
browsing for keys only shows picture and music app options?

### ISSUE THREAD

**Issue by Nanashi87** [HiddenRamblings/TagMo#123] opened 2018-03-05 08:51 UTC
Sgh-t999l tagmo app opens and says keys not loaded and when you click them to load them it doesn't have normal file browsing, it only shows google music, dropbox, gallery, music player, and photos.

**Comment by Bombastisch** [comment] 2018-03-05 12:51
Can you send a screenshot from that file browser which shows up, when you try to load the keys? Usually you can open a overview with the button on the top left.

**Comment by Nanashi87** [comment] 2018-03-07 04:04
I figured out  how to work around it with dropbox but here's what it shows
    On Monday, March 5, 2018, 4:52:04 AM PST, Basti <notifications@github.com> wrote:  
 
 
Can you send a screenshot from that file browser which shows up, when you try to load the keys? Usually you can open a overview with the button on the top left.

**Comment by DimensionsGaming** [comment] 2018-03-13 18:32
I had that problem before, but what I did to fix it was I installed a file explorer app from the play store, because it doesn't look as if the app selector sees the built in file explorer.

**Comment by Bombastisch** [comment] 2018-03-18 09:49
I opene an enhancement request, so maybe we get a file browser to circumvent that problem. The request is here: #126

Are you guys fine with closing this for now?

**Comment by Bombastisch** [comment] 2018-06-04 12:18
I think the issue is solved.  Request #126 is still open. My programming skills are sadly still not existent. :/

Maybe Hiddenrambler or North101 will return one day with a lot of new energy go push this project forward.
We still have a new UI that's not done yet, but it will improve TagMo a lot once finished. :)

**Closed** 2018-06-04 12:19 UTC
