### ISSUE TITLE
Logcat - TagMo #420566f4

### ISSUE THREAD

**Issue by LogcatGitHub** [HiddenRamblings/TagMo#584] opened 2022-10-02 04:00 UTC
*Submitted by jlaurenmiller5@*****.com*

Description:
---

I started to make a handful of amiibos (specifically the champion BotW amiibos), and every time I try to write it says "Failed to decrypt data". I initially thought it was an issue with the tags, but they can all be ready just fine. Not quite sure what the fix would be

Device info:
---
<table>
<tr><td>App version</td><td>3.1.6</td></tr>
<tr><td>App version code</td><td>316</td></tr>
<tr><td>Android build version</td><td>9014697</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TP1A.220905.004.A2</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>bluejay</td></tr>
<tr><td>Device model</td><td>Pixel 6a</td></tr>
<tr><td>Device product name</td><td>bluejay</td></tr>
<tr><td>Device hardware name</td><td>bluejay</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```
TagMo - #420566f4
Android TIRAMISU (13)
5.44 GB RAM
Installed by publish

--------- beginning of crash
10-01 22:53:42.496  8237  8335 E AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
10-01 22:53:42.496  8237  8335 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 8237
10-01 22:53:42.496  8237  8335 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{e73b657 8237:com.hiddenramblings.tagmo.eightbit/u0a295} (pid=8237, uid=10295) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5224)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7033)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3420)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1203)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:631)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:256)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:136)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6476)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2395)
10-01 22:53:42.496  8237  8335 E AndroidRuntime: 
10-01 22:53:59.058  8237  8359 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
10-01 22:53:59.058  8237  8359 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 8237
10-01 22:53:59.058  8237  8359 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{e73b657 8237:com.hiddenramblings.tagmo.eightbit/u0a295} (pid=8237, uid=10295) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5224)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7033)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3420)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1203)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:631)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:256)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:136)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6476)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2395)
10-01 22:53:59.058  8237  8359 E AndroidRuntime: 
10-01 22:54:23.739  8237  9504 E AndroidRuntime: FATAL EXCEPTION: pool-13-thread-1
10-01 22:54:23.739  8237  9504 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 8237
10-01 22:54:23.739  8237  9504 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{e73b657 8237:com.hiddenramblings.tagmo.eightbit/u0a295} (pid=8237, uid=10295) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5224)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7033)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3420)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1203)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:631)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:256)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:136)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6476)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2395)
10-01 22:54:23.739  8237  9504 E AndroidRuntime: 
10-01 22:58:40.700  8237 12435 E AndroidRuntime: FATAL EXCEPTION: pool-18-thread-1
10-01 22:58:40.700  8237 12435 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 8237
10-01 22:58:40.700  8237 12435 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{e73b657 8237:com.hiddenramblings.tagmo.eightbit/u0a295} (pid=8237, uid=10295) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5224)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7033)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3420)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1203)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:631)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:256)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:136)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6476)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2395)
10-01 22:58:40.700  8237 12435 E AndroidRuntime: 
--------- beginning of main
10-01 22:58:40.972  8237  8237 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
10-01 22:58:40.972  8237  8237 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```

**Comment by AbandonedCart** [comment] 2022-10-02 06:57
Fixed by https://github.com/HiddenRamblings/TagMo/commit/903fd25a9775a807ef099e492d73f25f0d052894, duplicate of https://github.com/HiddenRamblings/TagMo/issues/576

**Closed by AbandonedCart** 2022-10-02 06:57 UTC
