### ISSUE TITLE
"error getting tag data" on xiaomi MI9T

### ISSUE THREAD

**Issue by marvollo** [HiddenRamblings/TagMo#186] opened 2020-04-26 02:20 UTC
I have a xiaomi mi9t, android 10. However, every time I try to read the tag, I get an error "Error getting tag data. Possibly not a ntag215", but I'm sure it is a 215 tag.

Any solution for this kind of problem?

**Comment by Bombastisch** [comment] 2020-04-26 10:06
Can you try to read a original amiibo? One of those should defintely work, thus we can check if it's caused by your tag or your phone.

**Comment by marvollo** [comment] 2020-04-26 15:28
I don't have an original, but I have one made by this method on someone else's cell phone, and my cell phone reads normally in "Scan".

**Comment by AbandonedCart** [comment] 2021-09-11 13:48
Closing this as outdated, but please leave a comment if the issue needs to be opened again.

**Closed by AbandonedCart** 2021-09-11 13:48 UTC
