### ISSUE TITLE
Bank number and edit properties

### ISSUE THREAD

**Issue by Catflap62** [HiddenRamblings/TagMo#317] opened 2021-11-03 17:38 UTC
Scanning N2 Elite shows correct bank numbers, but selecting a bank shows bank number one lower than it should be.
![Screenshot_20211103-172120_TagMo](https://user-images.githubusercontent.com/43831308/140157270-27ad3d96-3b88-439e-a3ff-3f3d9556c375.jpg)
![Screenshot_20211103-172132_TagMo](https://user-images.githubusercontent.com/43831308/140157637-6ec8d6e9-09d5-4244-a1a3-651b42261140.jpg)

Selecting edit properties on a bank, scans the bank again but does not get correct properties. The Midna and Wolf Link amiibo I have on bank 1 has 40 hearts, but if I edit properties and scan bank again I get this
![Screenshot_20211103-172151_TagMo](https://user-images.githubusercontent.com/43831308/140162006-b183e33f-6b55-409f-8314-82689e04501a.jpg)

But if I turn off N2 Elite in settings so Tagmo only reads the active bank when I edit properties I get the correct properties
![Screenshot_20211103-172224_TagMo](https://user-images.githubusercontent.com/43831308/140162194-17cf6454-f52a-4d8f-b54a-cd25d2023417.jpg)

**Comment by AbandonedCart** [comment] 2021-11-03 18:00
It would appear that Mii, nickname, and write count are the only 3 fields being "decoded" and not simply read as raw bytes. I haven't tracked the cause, but it may be in how the bytes are collected during the read, since the difference between turning the elite support on and off changes that.

**Comment by AbandonedCart** [comment] 2021-11-03 18:19
I have to tear apart the entire read process and try to recreate the tag read in a way the N2 will accept. This may take a while.

**Comment by Catflap62** [comment] 2021-11-03 20:52
Do we need the folder icon where it shows N2 Elite ID, hopefully without it the whole ID would fit, I don't see the point of Scan as when you select Edit Properties or View Hex Code it will ask to Scan anyway, maybe Delete instead and all moved slightly to left so 3 dots is slightly easier to select. Activate Delete Write Replace ⋮ 
Sorry to be picky just trying to get it looking perfect, as I said before I am amazed at what you have achieved so quickly, many thanks.

**Comment by AbandonedCart** [comment] 2021-11-03 21:52
I can try moving it left more, but I may have to use some scaling tricks. It seems the average screen here is much smaller than mine.

![Screenshot_20211103-175214819](https://user-images.githubusercontent.com/1173913/140198218-84209c9d-a393-43ff-ae25-202de97720d7.png)

**Comment by Catflap62** [comment] 2021-11-03 21:55
Yes, you can see the difference in my screenshots, my phone is a Samsung Galaxy A71.

**Comment by Catflap62** [comment] 2021-11-03 22:23
Just been messing with font sizes on the phone and I can get it too fit now by going down one, if I go down three it looks close to yours but my eyes don't like that. So not a problem now.
![Screenshot_20211103-222006_TagMo](https://user-images.githubusercontent.com/43831308/140202097-06589d03-354e-438e-8896-b433d1e49ed7.jpg)

**Comment by AbandonedCart** [comment] 2021-11-03 22:27
You shouldn't have to change the font size of the whole phone over it. I'll try to get it to scale down a little smaller than the rest of the app. We can call it an "excess of information" issues

**Comment by AbandonedCart** [comment] 2021-11-04 00:18
See how https://github.com/HiddenRamblings/TagMo/commit/35ec156266e47f9bb92ec3f4cb635bb5a5e6ea38 looks. Android emulator is broken. Getting ready to downgrade soon, since they know and haven't fixed it.

**Comment by burndive** [comment] 2021-11-04 00:29
Things are visible, but the text is a bit too tiny. Maybe dial it back a notch.

![Screenshot_20211103-172727_TagMo](https://user-images.githubusercontent.com/19560779/140237379-b6b0b735-8fa3-494e-8512-ed906f4e4489.jpg)

**Comment by Catflap62** [comment] 2021-11-04 00:29
That definitely definitely works and makes it look like yours, but it is just a bit too small for my phone.
![Screenshot_20211104-002119_TagMo](https://user-images.githubusercontent.com/43831308/140237309-c3abf35a-0f97-495d-b7b6-5b7e9bba4a48.jpg)

**Comment by AbandonedCart** [comment] 2021-11-04 00:33
Yeah. That's smaller than I was hoping. Let me try to get an emulator that works.

**Comment by AbandonedCart** [comment] 2021-11-04 01:12
I'm not sure if the changes will fix it or cause the entire thing to crash and burn. 

It's some relatively dated code from a translation app I wrote a few years back. It wasn't physically possible to create the UI unless everyone used the dpi trick in their build.prop and not everyone wants that universally. It's meant to bring smaller screens into scale with a dpi mod, but leave phones using one or with screens larger than a Note 7 as is.

**Comment by Catflap62** [comment] 2021-11-04 01:13
That made it even smaller unfortunately.
![Screenshot_20211104-011223_TagMo](https://user-images.githubusercontent.com/43831308/140240779-34071ada-ff1f-4b30-8d19-f331244d6766.jpg)

**Comment by AbandonedCart** [comment] 2021-11-04 01:15
Oh ok. Looks like I went the wrong direction. That's an easy fix

**Comment by AbandonedCart** [comment] 2021-11-04 01:18
Might make more sense if I make a UI for the value and let it be configurable.

**Comment by Catflap62** [comment] 2021-11-04 01:23
Too far the other way.
![Screenshot_20211104-012253_TagMo](https://user-images.githubusercontent.com/43831308/140241580-9e3d6785-1b71-4281-b883-1a2d830dd9a0.jpg)

**Comment by Catflap62** [comment] 2021-11-04 01:37
I have been going back through old builds because I was sure I remembered one that did read the properties correctly on an N2 Elite.
Build 1a2b0a5 does it.

**Comment by AbandonedCart** [comment] 2021-11-04 01:40
I wonder if it's not detecting the elite properly in the handoff then.

**Comment by Catflap62** [comment] 2021-11-04 01:43
I just remember it wasn't working then did then wasn't again, so is there some code different in that build?

**Comment by Catflap62** [comment] 2021-11-04 01:52
93e6505 works then the one I have after doesn't e6aa946.
When you select edit properties in e6aa946 it goes to the scan tag screen itself, the builds that work tell you 'Amiibo data refresh required!'

**Comment by AbandonedCart** [comment] 2021-11-04 01:57
That lines up with it being a merge issue.

As for scale, it's not in settings. The min is 10 and max is 30. What you said was even smaller was 15 and too much the other way was 30. The original was 20. I set a default of 25.

**Comment by Catflap62** [comment] 2021-11-04 02:03
Slider seems to do nothing to the actual view.

**Comment by AbandonedCart** [comment] 2021-11-04 02:05
I remember the last slider being a pain, too. They really don't like to save values and display them. Always one or the other.

**Comment by Catflap62** [comment] 2021-11-04 02:33
Slider works but is all over the place and is messing up all views.

**Comment by AbandonedCart** [comment] 2021-11-04 04:05
I think I have the scale all worked out and I put in a workaround for the scanning. The N2 Elite app never legitimately scans Amiibo data, except as a blind read for a backup.

**Comment by burndive** [comment] 2021-11-04 04:59
Scanning works! Edit Properties is displayed correctly.  

Saving the edited data and then performing a Write operation resulted in the bank data being wiped, unfortunately.

Scaling is still smaller than I like set at 10 (slid all the way to the left).

If I set it larger, it gets super tiny, but then if I set it back to 10, it stays that small until I clear the app data entirely.

**Comment by burndive** [comment] 2021-11-04 05:02
Here's the default size, without any adjustment after clearing app data and launching for the first time.
![Screenshot_20211103-220122_TagMo](https://user-images.githubusercontent.com/19560779/140260639-0d3bf107-9958-4d7d-a7dc-986c39c9f59d.jpg)

**Comment by AbandonedCart** [comment] 2021-11-04 05:39
@Catflap62 As is, only the N2 viewer is going to be scaled and only because it has a lot more / lengthier buttons. The scale can be expanded to basically anything, so let me know if anything else looks cramped, but doesn't have items you can afford to lose. I finally got the emulator up, so I can see things.

The only way the serial fits without scale is to remove the icon and also kill the arrows. Putting the active bank there seems like it could cause confusion and some obligatory "slide me up" text could cause hiccups, since it would be displayed and removed depending on slide state.

**Comment by Catflap62** [comment] 2021-11-04 08:14
When I tick Scale N2 Browser View the slider is on 28, when I move slider it changes number, I go back to try but view size is the same, check settings and it shows 28 again.

**Comment by Catflap62** [comment] 2021-11-04 08:37
Edit properties works now.
Format should be Delete and still don't see the point of Scan Bank option in 3 dot menu.

**Comment by AbandonedCart** [comment] 2021-11-04 09:58
You're formatting the babk, not deleting it. Delete sounds like bank will be gone entirely.

Scan is there because it is once and done per instance. For someone that doesn't want top hit edit and find out it scans, they can scan first and then edit simply opens.

**Comment by AbandonedCart** [comment] 2021-11-04 14:27
We're going to close this one for now and a new one can be started for scale and menu stuff, if necessary. I think we've addressed the original issues, though. I'll be pushing through some cleanup shortly (~20 minutes).

**Closed by AbandonedCart** 2021-11-04 14:27 UTC
