### ISSUE TITLE
Slider is so random

### ISSUE THREAD

**Issue by Catflap62** [HiddenRamblings/TagMo#323] opened 2021-11-04 16:28 UTC
Trying to get the correct size with the slider for my phone is not working, the best setting I had was before the slider builds and I made the phone font one lower. For me personally I would prefer no slider at all.

**Comment by AbandonedCart** [comment] 2021-11-04 16:30
The checkbox disables it.

**Comment by Catflap62** [comment] 2021-11-04 16:32
I know it does, but now when try font one lower it does not affect the N2 view only the rest of Tagmo.

**Comment by AbandonedCart** [comment] 2021-11-04 16:33
Did you kill the app (recents, swipe it away) after disabling the checkbox?

For now, that is how to fully reset it. The rest of the code to dynamically reset isn't finished.

**Comment by Catflap62** [comment] 2021-11-04 16:41
Yes, I just really dislike the slider it affects all of Tagmo, I choose a number the view goes ridiculously small, I go into settings and that is ridiculously small as well, I make it bigger and it's just random. I can't get it to go one lower than it is when not using it.

**Comment by AbandonedCart** [comment] 2021-11-04 16:45
Alright. Best bet is to disable it and leave it that way.

**Comment by burndive** [comment] 2021-11-04 16:53
Even if I never enable the Scaling checkbox in Settings, as soon as I scan the N2 Elite, the interface is to small, and it propagates to every other interface in the app.

**Comment by AbandonedCart** [comment] 2021-11-04 16:55
The code you have installed is absolute. It cannot be changed until the entire apk is updated.

**Comment by burndive** [comment] 2021-11-04 17:02
I cleared the app data after installing the latest update, never checked the box to Scale N2 Browser View, and that is what I saw.

**Comment by AbandonedCart** [comment] 2021-11-04 17:03
The code you have installed is absolute. It cannot be changed until the entire apk is updated.

**Comment by burndive** [comment] 2021-11-04 17:03
Here's a screenshot after opening the app, scanning the N2, and pressing the back button to exit that interface, and then scrolling down half a screen.
![Screenshot_20211104-100225_TagMo](https://user-images.githubusercontent.com/19560779/140385430-82d9a4ed-ed21-470e-b892-eff6c90def72.jpg)

**Comment by burndive** [comment] 2021-11-04 17:05
Oh, I thought you said it was already in the latest.

**Comment by AbandonedCart** [comment] 2021-11-04 17:54
Just like last time, the slider itself is the cause of issues. Enable scaling and you get 2.5 or disable it for stock views. If it doesn't immediately refresh the browser, swipe down to force a refresh. That is still touchy.

**Comment by AbandonedCart** [comment] 2021-11-04 17:59
Large screen - Original vs Scaled

![Screenshot_20211104-135642400_1](https://user-images.githubusercontent.com/1173913/140394045-771699a5-91f3-4a43-803e-a597eb5bd2c5.jpg)


![Screenshot_20211104-135655954_1](https://user-images.githubusercontent.com/1173913/140394061-238f0794-7a71-42f6-b01e-0464a411d928.jpg)

**Comment by AbandonedCart** [comment] 2021-11-04 18:02
Small screen - Original vs Scaled

![Screenshot_20211104-140029519_1](https://user-images.githubusercontent.com/1173913/140394530-6a0d3b26-6d9a-4c31-8b08-5071910863f4.jpg)


![Screenshot_20211104-140045341_1](https://user-images.githubusercontent.com/1173913/140394538-b8c51549-327f-4bd1-b1f0-eaa9a1c37456.jpg)

**Comment by AbandonedCart** [comment] 2021-11-04 18:16
Closing this out for removal of the slider

**Closed by AbandonedCart** 2021-11-04 18:16 UTC
