### ISSUE TITLE
[Bug]: Tagmo keeps freezing

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#575] opened 2022-09-27 19:47 UTC
### Issue Description

Hello I just updated and the new version loads and then after about 10 seconds it just freezes and I can't do anything sorry I don't know how to make the log file because it froze.  Thank you.

### Logcat Output

```shell
I don't know how to make one when it freezes
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment] 2022-09-27 19:52
Closing as duplicate of https://github.com/HiddenRamblings/TagMo/issues/574

**Closed by AbandonedCart** 2022-09-27 19:52 UTC

**Comment by AbandonedCart** [comment] 2022-09-27 20:25
That's fine. Android 13 is not widely distributed yet, but the chances it is unrelated are like 2%.
