### ISSUE TITLE
Writing not working 

### ISSUE THREAD

**Issue by LogcatGitHub** [HiddenRamblings/TagMo#580] opened 2022-09-30 00:57 UTC
*Submitted by retrotaco15@*****.com*

Description:
---

Doesn't write into tag

Device info:
---
<table>
<tr><td>App version</td><td>3.1.6</td></tr>
<tr><td>App version code</td><td>316</td></tr>
<tr><td>Android build version</td><td>G986USQS2EVB3</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.G986USQS2EVB3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>y2q</td></tr>
<tr><td>Device model</td><td>SM-G986U</td></tr>
<tr><td>Device product name</td><td>y2qsqw</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```
TagMo - #420566f4
Android S (12)
10.35 GB RAM
Installed by publish

--------- beginning of crash
09-29 19:53:36.440 23406 30819 E AndroidRuntime: FATAL EXCEPTION: pool-187-thread-1
09-29 19:53:36.440 23406 30819 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 23406
09-29 19:53:36.440 23406 30819 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{18c051c 23406:com.hiddenramblings.tagmo.eightbit/u0a374} (pid=23406, uid=10374) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2421)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2404)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2346)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6793)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7743)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3526)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1210)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1158)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1114)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:796)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:329)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:168)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:142)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7577)
09-29 19:53:36.440 23406 30819 E AndroidRuntime: 
09-29 19:54:08.159 23406 30986 E AndroidRuntime: FATAL EXCEPTION: pool-188-thread-1
09-29 19:54:08.159 23406 30986 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 23406
09-29 19:54:08.159 23406 30986 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{18c051c 23406:com.hiddenramblings.tagmo.eightbit/u0a374} (pid=23406, uid=10374) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2421)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2404)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2346)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6793)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7743)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3526)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1210)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1158)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1114)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:796)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:329)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:168)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:142)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7577)
09-29 19:54:08.159 23406 30986 E AndroidRuntime: 
--------- beginning of main
09-29 19:54:12.770 23406 23406 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
09-29 19:54:12.781 23406 23406 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
09-29 19:54:12.795 23406 23406 W IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
09-29 19:54:12.808 23406 23406 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
09-29 19:54:12.809 23406 23406 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
09-29 19:54:12.817 23406 23406 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
09-29 19:55:55.994 32332 32332 E .tagmo.eightbi: Not starting debugger since process cannot load the jdwp agent.
09-29 19:55:55.995 32332 32332 E USNET   : USNET: appName: com.hiddenramblings.tagmo.eightbit
09-29 19:55:56.023 32332 32332 W ziparchive: Unable to open '/data/app/~~XKApRcohatzRt_MYgVTBfg==/com.hiddenramblings.tagmo.eightbit-0wh08LI_ab8xM6B4Ys1xlg==/split_config.arm64_v8a.dm': No such file or directory
09-29 19:55:56.023 32332 32332 W ziparchive: Unable to open '/data/app/~~XKApRcohatzRt_MYgVTBfg==/com.hiddenramblings.tagmo.eightbit-0wh08LI_ab8xM6B4Ys1xlg==/split_config.arm64_v8a.dm': No such file or directory
09-29 19:55:56.023 32332 32332 W .tagmo.eightbi: Entry not found
09-29 19:55:56.023 32332 32332 W ziparchive: Unable to open '/data/app/~~XKApRcohatzRt_MYgVTBfg==/com.hiddenramblings.tagmo.eightbit-0wh08LI_ab8xM6B4Ys1xlg==/split_config.en.dm': No such file or directory
09-29 19:55:56.023 32332 32332 W ziparchive: Unable to open '/data/app/~~XKApRcohatzRt_MYgVTBfg==/com.hiddenramblings.tagmo.eightbit-0wh08LI_ab8xM6B4Ys1xlg==/split_config.en.dm': No such file or directory
09-29 19:55:56.026 32332 32332 W .tagmo.eightbi: Entry not found
09-29 19:55:56.026 32332 32332 W ziparchive: Unable to open '/data/app/~~XKApRcohatzRt_MYgVTBfg==/com.hiddenramblings.tagmo.eightbit-0wh08LI_ab8xM6B4Ys1xlg==/split_config.xxhdpi.dm': No such file or directory
09-29 19:55:56.026 32332 32332 W ziparchive: Unable to open '/data/app/~~XKApRcohatzRt_MYgVTBfg==/com.hiddenramblings.tagmo.eightbit-0wh08LI_ab8xM6B4Ys1xlg==/split_config.xxhdpi.dm': No such file or directory
09-29 19:55:56.026 32332 32332 W .tagmo.eightbi: Entry not found
09-29 19:55:56.028 32332 32332 W .tagmo.eightbi: JIT profile information will not be recorded: profile file does not exist.
09-29 19:55:56.028 32332 32332 W .tagmo.eightbi: JIT profile information will not be recorded: profile file does not exist.
09-29 19:55:56.028 32332 32332 W .tagmo.eightbi: JIT profile information will not be recorded: profile file does not exist.
09-29 19:55:56.069 32332 32360 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
09-29 19:55:56.069 32332 32360 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 32332
09-29 19:55:56.069 32332 32360 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{590237e 32332:com.hiddenramblings.tagmo.eightbit/u0a374} (pid=32332, uid=10374) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2421)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2404)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2346)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6793)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7743)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3526)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1210)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1158)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1114)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:796)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:329)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:168)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:142)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7577)
09-29 19:55:56.069 32332 32360 E AndroidRuntime: 
09-29 19:55:56.082 32332 32367 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
09-29 19:55:56.082 32332 32367 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 32332
09-29 19:55:56.082 32332 32367 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{590237e 32332:com.hiddenramblings.tagmo.eightbit/u0a374} (pid=32332, uid=10374) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2421)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2404)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2346)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6793)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7743)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3526)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1210)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1158)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1114)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-29 19:55:56.082 32332 32367 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-29 19:55:56.153 32332 32332 W View    : requestLayout() improperly called by android.widget.FrameLayout{71089e3 V.E..V... ......ID 0,0-1080,1966 #2} during layout: running second layout pass
09-29 19:55:56.153 32332 32332 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{4a00fe0 VFED.V... ......ID 0,1013-1080,1963 #7f09010f app:id/foomiibo_list} during layout: running second layout pass
09-29 19:55:56.153 32332 32332 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{43d3299 VFED.V... ......ID 0,0-1080,1013 #7f09005f app:id/amiibos_list} during layout: running second layout pass
09-29 19:55:56.182 32332 32383 E AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
09-29 19:55:56.182 32332 32383 E AndroidRuntime: Process: com.hiddenramblings.tagmo.eightbit, PID: 32332
09-29 19:55:56.182 32332 32383 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{590237e 32332:com.hiddenramblings.tagmo.eightbit/u0a374} (pid=32332, uid=10374) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2421)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2404)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2346)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6793)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7743)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3526)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1210)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1158)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1114)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-29 19:55:56.182 32332 32383 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-29 19:55:58.697 32332 32344 W JavaBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.internal.zzai
```

**Comment by AbandonedCart** [comment] 2022-09-30 01:23
Duplicate of https://github.com/HiddenRamblings/TagMo/issues/578

**Closed by AbandonedCart** 2022-09-30 01:23 UTC
