### ISSUE TITLE
Logcat - TagMo #db97a5c

### ISSUE THREAD

**Issue by LogcatGitHub** [HiddenRamblings/TagMo#513] opened 2022-07-19 20:52 UTC
*Submitted by mewthree19@*******.com*

Description:
---

Issue with writing to ntag

Device info:
---
<table>
<tr><td>App version</td><td>2.9.8</td></tr>
<tr><td>App version code</td><td>298</td></tr>
<tr><td>Android build version</td><td>00WW_5_22D</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>00WW_5_22D</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>NE1</td></tr>
<tr><td>Device model</td><td>TA-1020</td></tr>
<tr><td>Device product name</td><td>TA-1020_00WW</td></tr>
<tr><td>Device hardware name</td><td>mt6735</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```
TagMo - #db97a5c
Android P (9)

--------- beginning of crash
07-19 14:19:42.950  8676  8676 E AndroidRuntime: FATAL EXCEPTION: main
07-19 14:19:42.950  8676  8676 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 8676
07-19 14:19:42.950  8676  8676 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=685555169, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.browser.BrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)' on a null object reference
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4433)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)' on a null object reference
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.FlaskSlotFragment.scanBluetoothServices(FlaskSlotFragment.java:615)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.FlaskSlotFragment.selectBluetoothDevice(FlaskSlotFragment.java:647)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.FlaskSlotFragment.onAdapterEnabled(FlaskSlotFragment.java:917)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.BluetoothEnabler.lambda$new$4(BluetoothEnabler.java:149)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.BluetoothEnabler.$r8$lambda$p3XBAUlYKh6ZD19Wt3ObgwuOZ5w(Unknown Source:0)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at com.hiddenramblings.tagmo.eightbit.bluetooth.BluetoothEnabler$$ExternalSyntheticLambda4.onActivityResult(Unknown Source:8)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onRequestPermissionsResult(ComponentActivity.java:667)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:612)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4384)
07-19 14:19:42.950  8676  8676 E AndroidRuntime: 	... 11 more
07-19 15:42:38.369 10012 10012 E AndroidRuntime: FATAL EXCEPTION: main
07-19 15:42:38.369 10012 10012 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 10012
07-19 15:42:38.369 10012 10012 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=835; index=835
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at java.util.ArrayList.clear(ArrayList.java:569)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.adapter.BrowserAdapter.onBrowserSettingsChanged(BrowserAdapter.java:85)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.hiddenramblings.tagmo.settings.BrowserSettings.notifyChanges(BrowserSettings.java:313)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$34(BrowserActivity.java:1658)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$k5_Ph6WV6bVxzjCKtIot_rNWGs4(Unknown Source:0)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda76.run(Unknown Source:4)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-19 15:42:38.369 10012 10012 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: FATAL EXCEPTION: main
07-19 15:52:52.949 12652 12652 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 12652
07-19 15:52:52.949 12652 12652 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.material.bottomsheet.BottomSheetBehavior.getState()' on a null object reference
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.onBackPressed(BrowserActivity.java:2611)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.app.Activity.onKeyUp(Activity.java:3082)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.KeyEvent.dispatch(KeyEvent.java:2716)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.app.Activity.dispatchKeyEvent(Activity.java:3365)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3089)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:343)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5206)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5069)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4586)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4639)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4605)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4745)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4613)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4802)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4586)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4639)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4605)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4613)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4586)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4639)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4605)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4778)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4943)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:326)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:160)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-19 15:52:52.949 12652 12652 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: FATAL EXCEPTION: main
07-19 19:00:25.090 31540 31540 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 31540
07-19 19:00:25.090 31540 31540 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=835; index=835
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at java.util.ArrayList.clear(ArrayList.java:569)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.adapter.BrowserAdapter.onBrowserSettingsChanged(BrowserAdapter.java:85)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.hiddenramblings.tagmo.settings.BrowserSettings.notifyChanges(BrowserSettings.java:313)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$34(BrowserActivity.java:1658)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$k5_Ph6WV6bVxzjCKtIot_rNWGs4(Unknown Source:0)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda76.run(Unknown Source:4)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-19 19:00:25.090 31540 31540 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
--------- beginning of main
07-19 21:48:04.923 16234 16234 D View    : [Warning] assignParent to null: this = DecorView@7a8b26[NfcActivity]
07-19 21:48:05.019 16234 17465 W IOException: java.io.IOException: /storage/emulated/0/Amiibo/key_retail.bin size: 160, Expected: 532
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$35(BrowserActivity.java:1643)
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$GBOrlgjls8Z0JOy3UIoX9n3pHwI(Unknown Source:0)
07-19 21:48:05.019 16234 17465 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
07-19 21:48:05.019 16234 17465 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-19 21:48:05.019 16234 17465 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-19 21:48:05.019 16234 17465 W IOException: 	at java.lang.Thread.run(Thread.java:764)
07-19 21:48:05.052 16234 16268 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
07-19 21:48:05.373 16234 16268 W libEGL  : EGLNativeWindowType 0x711d082010 disconnect failed
07-19 21:48:05.377 16234 16268 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
07-19 21:48:05.739 16234 16240 I ramblings.tagm: Background concurrent copying GC freed 10728(578KB) AllocSpace objects, 0(0B) LOS objects, 20% free, 23MB/29MB, paused 558us total 178.142ms
07-19 21:48:06.103 16234 16240 I ramblings.tagm: Background concurrent copying GC freed 54772(1949KB) AllocSpace objects, 2(9MB) LOS objects, 21% free, 21MB/27MB, paused 206us total 239.077ms
07-19 21:48:07.645 16234 16234 D ViewRootImpl[PopupWindow:4a995ff]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
07-19 21:48:07.697 16234 16268 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
```

**Comment by AbandonedCart** [comment] 2022-07-20 04:34
Closing as a duplicate of https://github.com/HiddenRamblings/TagMo/issues/512

**Closed by AbandonedCart** 2022-07-20 04:34 UTC
